In [3]:
import numpy as np

In [3]:
a = [x for x in range(1000)]


In [4]:
a

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
A = np.arange(1000, dtype=np.uint8)

In [6]:
A

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [9]:
B = np.arange(0,100, 2)

In [10]:
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [4]:
my_arr = [[1,2,3,4],[4,5,6,7]]
np_arr = np.array(my_arr)

In [5]:
np_arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [13]:
type(np_arr)

numpy.ndarray

In [14]:
np_arr[0]

array([1, 2, 3, 4])

In [6]:
np_arr[:,1]

array([2, 5])

In [7]:
np_arr[:,1:]

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
np_arr[:,0]

array([1, 4])

In [9]:
np_arr[:,-1]

array([4, 7])

In [46]:
N = 8

In [47]:
D = np.random.rand(N,N).astype(np.float32)

In [48]:
D

array([[0.1120389 , 0.3978556 , 0.96947044, 0.8655071 , 0.8170721 ,
        0.25790283, 0.17088759, 0.66864324],
       [0.929376  , 0.5567629 , 0.5716127 , 0.27997908, 0.7694929 ,
        0.18704374, 0.32367924, 0.42543644],
       [0.5076104 , 0.24240974, 0.11483683, 0.61062   , 0.28863055,
        0.5812382 , 0.15436271, 0.4811401 ],
       [0.53258944, 0.05182354, 0.33660427, 0.13441467, 0.06337497,
        0.98996025, 0.32235384, 0.8098745 ],
       [0.25464067, 0.6815027 , 0.76022786, 0.59563875, 0.47157618,
        0.41184092, 0.34886828, 0.92952913],
       [0.8306194 , 0.9650269 , 0.12429722, 0.73086745, 0.9383405 ,
        0.18123306, 0.06649627, 0.74112064],
       [0.57447314, 0.84182876, 0.13977237, 0.7952673 , 0.20162731,
        0.16365594, 0.1642658 , 0.8145747 ],
       [0.6651972 , 0.52306545, 0.35883048, 0.87720054, 0.39244512,
        0.8165994 , 0.4391349 , 0.37694442]], dtype=float32)

In [49]:
E = np.zeros((N,N), dtype=np.float32)

In [50]:
E

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [51]:
I = np.eye(N,N)

In [52]:
I

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [53]:
T = np.random.randn(N, N)

In [54]:
T

array([[-1.87079192, -0.35151348,  0.01841838,  1.67643731,  0.32692737,
        -0.21910053,  0.82940558, -2.21113531],
       [ 0.23561456,  0.77086519, -1.47858625,  1.14375404,  0.33849641,
        -0.41528791,  0.63278187,  2.27069286],
       [ 0.18186626,  0.24822059, -0.4593609 , -0.84984437,  0.83033582,
        -0.85608383,  0.07156624, -0.47765745],
       [ 0.47897983,  0.33366211,  1.03753994, -0.5100164 , -0.26987494,
        -0.97876372, -0.44429326,  0.37730049],
       [ 0.75698862, -0.92216532,  0.86960592,  1.35563786,  0.4134349 ,
         1.87679581, -0.7737892 , -1.2446547 ],
       [-1.77872025,  1.49604431,  0.65436566, -0.05558467,  0.27996863,
        -1.12548905,  2.44575198,  0.12922118],
       [ 0.10939479,  0.72576662,  0.48100923,  0.22388402, -0.79047446,
         0.47146836,  1.8820245 ,  1.34542005],
       [ 1.59318663, -0.51121568, -0.98960482, -0.12578692,  0.05572491,
         1.09419152, -1.69246463,  1.52955032]])

In [55]:
l = [[2,3,4,5],
     [4,3,5,2],
     [1,2,3,4],
     [9,2,3,4]]

In [56]:
A = np.array(l)

In [57]:
A

array([[2, 3, 4, 5],
       [4, 3, 5, 2],
       [1, 2, 3, 4],
       [9, 2, 3, 4]])

In [58]:
A[:2,2:]

array([[4, 5],
       [5, 2]])

In [30]:
A[2:,1:3]

array([[2, 3],
       [2, 3]])

In [35]:
np.random.seed(42)

In [64]:
A = np.random.randn(N,N).astype(np.float32)

In [63]:
B = np.random.randn(N,N).astype(np.float32)

In [38]:
A

array([[ 0.49671414, -0.1382643 ,  0.64768857,  1.5230298 , -0.23415338,
        -0.23413695,  1.5792128 ,  0.7674347 , -0.46947438,  0.54256004,
        -0.46341768, -0.46572974,  0.24196227, -1.9132802 , -1.7249179 ,
        -0.5622875 ],
       [-1.0128311 ,  0.31424734, -0.9080241 , -1.4123037 ,  1.4656488 ,
        -0.2257763 ,  0.0675282 , -1.4247482 , -0.54438275,  0.11092259,
        -1.1509936 ,  0.37569803, -0.6006387 , -0.29169375, -0.6017066 ,
         1.8522782 ],
       [-0.01349723, -1.0577109 ,  0.82254493, -1.2208437 ,  0.2088636 ,
        -1.9596701 , -1.328186  ,  0.19686124,  0.73846656,  0.17136829,
        -0.11564828, -0.30110368, -1.478522  , -0.7198442 , -0.46063876,
         1.0571222 ],
       [ 0.3436183 , -1.7630402 ,  0.32408398, -0.38508227, -0.676922  ,
         0.6116763 ,  1.0309995 ,  0.93128014, -0.83921754, -0.3092124 ,
         0.33126342,  0.9755451 , -0.47917423, -0.18565898, -1.1063349 ,
        -1.1962066 ],
       [ 0.8125258 ,  1.35624   , -0

In [65]:
A + B

array([[-1.0211403 ,  1.5753944 ,  4.139657  , -0.61891997,  0.72908646,
        -0.98496103, -1.379439  ,  0.85214865],
       [-1.6311078 ,  1.0446509 ,  0.67306703, -0.32825208,  2.1829083 ,
        -0.02579957,  1.6061323 , -1.7842135 ],
       [-0.77660084,  0.42730084, -1.1971555 ,  1.0030818 ,  0.34415323,
        -0.84289306,  0.6693665 ,  3.0658858 ],
       [-0.07794952,  0.54978377,  0.21078163, -0.09629706, -0.70755285,
        -0.47194433,  1.8501225 , -0.36305863],
       [-0.5607767 , -0.805333  , -1.6332796 ,  1.6860846 ,  0.16336787,
        -0.8342434 ,  1.5758237 ,  1.8256339 ],
       [ 0.32549512, -0.9037463 ,  0.38198617, -0.1278185 ,  0.22404808,
         1.7010324 ,  0.04518655, -1.2770458 ],
       [-0.12356305, -1.6255374 , -0.21999863,  1.3548267 ,  0.9293665 ,
         0.42034274,  1.0154216 , -0.29716718],
       [ 2.7939827 ,  0.35876203, -0.40715545,  2.109641  ,  0.16460305,
         3.2560549 ,  2.8828263 , -0.72213066]], dtype=float32)

In [40]:
A @ B

array([[ 2.01100135e+00, -3.49316329e-01,  2.92026615e+00,
        -4.17115402e+00,  6.32559657e-01,  3.84469318e+00,
         3.16445780e+00,  3.83602834e+00,  3.68828917e+00,
        -2.22582817e+00,  3.26502061e+00, -2.09240508e+00,
        -1.15379006e-01,  5.41058123e-01, -8.09029484e+00,
        -3.88812494e+00],
       [-4.04904842e+00,  4.06622362e+00, -5.47725630e+00,
        -1.48389518e+00, -2.00363517e+00, -1.73301291e+00,
         9.86623764e-02,  3.72450066e+00, -3.45834470e+00,
        -2.98246574e+00, -8.02406502e+00, -1.75157976e+00,
         1.71081543e-01,  6.31302476e-01,  2.46183705e+00,
         1.83476162e+00],
       [-1.60173345e+00,  1.90065718e+00, -2.51943159e+00,
         6.39217257e-01,  3.42349529e+00,  3.65858197e+00,
        -2.16931701e-01,  4.78230524e+00, -1.20966625e+00,
        -2.82925653e+00,  1.52493358e+00,  3.46248722e+00,
        -7.98472023e+00,  3.13537574e+00, -2.35997820e+00,
        -3.10309029e+00],
       [ 1.91884041e+00,  6.38398170e

In [66]:
np.dot(A,B)

array([[-4.4081697 ,  2.6911387 , -0.06267627, -0.7342439 , -0.60662127,
        -1.2722559 , -2.2784078 ,  0.23782176],
       [ 1.8790038 , -3.7877455 , -4.889888  ,  2.0479276 ,  0.24524668,
         0.8738768 , -0.00898638, -1.4055823 ],
       [ 2.1619034 ,  3.36721   ,  0.76882637,  1.5405099 , -0.9286571 ,
         5.0335264 ,  6.2157397 , -3.3045673 ],
       [ 3.416106  , -3.0646749 , -1.9343992 , -2.7355783 ,  0.71876603,
         0.3595897 , -0.38370264, -3.2827344 ],
       [ 1.9952147 ,  2.3099756 , -1.7348143 ,  1.910067  ,  1.1597595 ,
         4.172006  ,  5.778592  , -4.638719  ],
       [ 2.204784  , -2.9167802 , -2.136876  , -0.4005427 , -1.6646799 ,
        -2.2159696 , -1.5198649 , -0.62260807],
       [ 2.6470633 ,  2.0719576 , -1.8675712 ,  1.9719412 , -2.8945303 ,
        -1.4277295 ,  3.1022427 , -1.471632  ],
       [ 2.3738854 , -2.069819  ,  6.302278  , -0.54360557,  2.6096015 ,
        -3.871753  ,  0.05006689,  3.6253777 ]], dtype=float32)

In [67]:
A

array([[-0.44550252,  1.4533845 ,  1.5795722 , -0.52286005, -0.42018682,
        -0.2817846 , -1.3444505 , -0.91865194],
       [-1.0041407 , -0.7677976 , -0.03468489,  0.23421474,  1.5505005 ,
        -0.998354  ,  0.98432237, -0.21398884],
       [-0.04946371,  0.67481947, -1.122722  ,  0.38240975,  0.16645221,
         0.49245125,  0.28916866,  2.4553    ],
       [-0.63773996, -0.530997  , -0.6231405 , -0.55547714, -0.63738716,
         1.1890166 ,  1.4205042 , -0.5707463 ],
       [-0.83235556,  0.47141555, -0.552223  ,  0.6329318 ,  0.20292301,
        -1.5157441 ,  1.5475053 ,  1.7958777 ],
       [-0.6127887 , -0.38770157,  0.2858654 ,  0.3344568 ,  0.6585443 ,
         2.0102046 , -0.17694722, -0.7982972 ],
       [-1.3793192 , -0.73093003, -0.03312697,  1.7945578 , -0.5176113 ,
         0.22378795, -0.0164229 ,  1.1883932 ],
       [ 2.5269325 , -0.53086877, -0.48943943,  1.0441608 ,  0.6818915 ,
         1.8467073 ,  0.58392817, -0.3592921 ]], dtype=float32)

In [68]:
A

array([[-0.44550252,  1.4533845 ,  1.5795722 , -0.52286005, -0.42018682,
        -0.2817846 , -1.3444505 , -0.91865194],
       [-1.0041407 , -0.7677976 , -0.03468489,  0.23421474,  1.5505005 ,
        -0.998354  ,  0.98432237, -0.21398884],
       [-0.04946371,  0.67481947, -1.122722  ,  0.38240975,  0.16645221,
         0.49245125,  0.28916866,  2.4553    ],
       [-0.63773996, -0.530997  , -0.6231405 , -0.55547714, -0.63738716,
         1.1890166 ,  1.4205042 , -0.5707463 ],
       [-0.83235556,  0.47141555, -0.552223  ,  0.6329318 ,  0.20292301,
        -1.5157441 ,  1.5475053 ,  1.7958777 ],
       [-0.6127887 , -0.38770157,  0.2858654 ,  0.3344568 ,  0.6585443 ,
         2.0102046 , -0.17694722, -0.7982972 ],
       [-1.3793192 , -0.73093003, -0.03312697,  1.7945578 , -0.5176113 ,
         0.22378795, -0.0164229 ,  1.1883932 ],
       [ 2.5269325 , -0.53086877, -0.48943943,  1.0441608 ,  0.6818915 ,
         1.8467073 ,  0.58392817, -0.3592921 ]], dtype=float32)

In [69]:
N

8

In [70]:
A.size

64

In [71]:
A.shape

(8, 8)

In [72]:
A.ndim

2

In [76]:
dnp = [
    [2,3,4,5,5],
    [9,9,2,4,5]
     ]

In [78]:
dnp = np.array(d)

In [79]:
dnp


array([[2, 3, 4, 5, 5],
       [9, 9, 2, 4, 5]])

In [80]:
dnp.T

array([[2, 9],
       [3, 9],
       [4, 2],
       [5, 4],
       [5, 5]])